name: Build & Release Game

on:
  push:
    tags:
      - 'v*.*.*' # Triggers on semantic version tags (e.g., v1.0.0)

env:
  GODOT_VERSION: 4.7.1 # Specify your Godot version
  EXPORT_NAME: Solitaire

jobs:
  export-and-deploy:
    name: Export Godot Project & Deploy
    runs-on: ubuntu-latest

    permissions:
      contents:  write

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5
        with:
          lfs: true # Enable if using Git LFS for assets

      - name: Export Game (Godot CI)
        id: export
        uses: firebelley/godot-export@v8.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-stable/Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-stable/Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true

      - name: create release
        uses: ncipollo/release-action@v1.18.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*

      - name: deploy to itch.io
        uses: yeslayla/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: windows
          ITCH_GAME: first-project-solitaire
          ITCH_USER: VortexAI
          PACKAGE: build/windows

      # - name: Deploy to Itch.io (Butler)
      #   uses: ManleyDev/butler-publish-itchio-action@v2.3.0
      #   env:
      #     BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
      #     CHANNEL: linux # Matches your build channel name
      #     GAME_PATH: build/builds/Linux
      #     ITALICS_USER: your-itch-username
      #     ITALICS_GAME: your-itch-game-slug
      #     VERSION: ${{ github.ref_name }}
